name: guia_de_moteis_go_replica
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  preload_page_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
